version: '3'

services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    networks:
      - net
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb:

networks:
  net:
    driver: bridge