version: '3'

services:
  mongodb:
    image: mongo:5
    restart: unless-stopped
    networks:
      - net
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'

  mongoexpress:
    image: mongo-express:1.0.0-alpha.4
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - net
volumes:
  mongodb:

networks:
  net:
    driver: bridge
